server: 
  port: 8899
#  servlet:
#    context-path: /jwt
  
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/db_VueWebSyc?useUnicode=true&characterEncoding=UTF-8&zeroDateTimeBehavior=convertToNull&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver

battcn:
  security:
    token:
      refresh-exp-time: 30 
      expiration-time: 10 
      signing-key: battcn